version: '3.4'

services:
  orchestrator:
    build: .
    ports:
      - "8080:8080"
    environment:
    - GCP_PROJECT_ID=deklerk-sandbox
    - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    - PORT=8080
    command:
      - /bin/sh
      - -cex
      - |
        cd orchestrator
        rm -rf node_modules
        npm install
        ./node_modules/.bin/webpack --progress
        go run *.go
  http_receiver:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/http/*.go
  batch_http_receiver:
    build: .
    ports:
      - "8087:8087"
    environment:
      - PORT=8087
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/batch_http/*.go
  udp_receiver:
    build: .
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/udp/*.go
  unary_grpc_receiver:
    build: .
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/unary_grpc/*.go
  streaming_grpc_receiver:
    build: .
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/streaming_grpc/*.go
  streaming_websocket_receiver:
    build: .
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/streaming_websocket/*.go
  quic_receiver:
    build: .
    ports:
      - "8086:8086"
    environment:
      - PORT=8086
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - PRIVATE_KEY_FILE=/go/src/deklerk-startup-project/receivers/quic/dummy_key.unencrypted.pem
      - CERT_FILE=/go/src/deklerk-startup-project/receivers/quic/dummy_cert.pem
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/quic/*.go
  http_sender:
    build: .
    links:
      - http_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - HTTP_RECEIVER_IP=http_receiver
      - HTTP_RECEIVER_PORT=8081
    command:
      - /bin/sh
      - -c
      - |
        go run senders/http/*.go
  batch_http_sender:
    build: .
    links:
      - batch_http_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - BATCH_HTTP_RECEIVER_IP=batch_http_receiver
      - BATCH_HTTP_RECEIVER_PORT=8087
    command:
      - /bin/sh
      - -c
      - |
        go run senders/batch_http/*.go
  udp_sender:
    build: .
    links:
      - udp_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - UDP_RECEIVER_IP=udp_receiver
      - UDP_RECEIVER_PORT=8082
    command:
      - /bin/sh
      - -c
      - |
        go run senders/udp/*.go
  unary_grpc_sender:
    build: .
    links:
      - unary_grpc_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - UNARY_GRPC_RECEIVER_IP=unary_grpc_receiver
      - UNARY_GRPC_RECEIVER_PORT=8083
    command:
      - /bin/sh
      - -c
      - |
        go run senders/unary_grpc/*.go
  streaming_grpc_sender:
    build: .
    links:
      - streaming_grpc_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - STREAMING_GRPC_RECEIVER_IP=streaming_grpc_receiver
      - STREAMING_GRPC_RECEIVER_PORT=8084
    command:
      - /bin/sh
      - -c
      - |
        go run senders/streaming_grpc/*.go
  streaming_websocket_sender:
    build: .
    links:
      - streaming_websocket_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - STREAMING_WEBSOCKET_RECEIVER_IP=streaming_websocket_receiver
      - STREAMING_WEBSOCKET_RECEIVER_PORT=8085
    command:
      - /bin/sh
      - -c
      - |
        go run senders/streaming_websocket/*.go
  quic_sender:
    build: .
    links:
      - quic_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - QUIC_RECEIVER_IP=quic_receiver
      - QUIC_RECEIVER_PORT=8086
    command:
      - /bin/sh
      - -c
      - |
        go run senders/quic/*.go