version: '3.4'

services:
  orchestrator:
    build: .
    ports:
      - "8080:8080"
    environment:
    - GCP_PROJECT_ID=deklerk-sandbox
    - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    - PORT=8080
    command:
      - /bin/sh
      - -cex
      - |
        cd orchestrator
        rm -rf node_modules
        npm install
        ./node_modules/.bin/webpack --progress
        go run *.go
  http_receiver:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/http/*.go
  udp_receiver:
    build: .
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
    command:
      - /bin/sh
      - -c
      - |
        go run receivers/udp/*.go
  http_sender:
    build: .
    links:
      - http_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - HTTP_RECEIVER_IP=http_receiver
      - HTTP_RECEIVER_PORT=8081
    command:
      - /bin/sh
      - -c
      - |
        go run senders/http/*.go
  udp_sender:
    build: .
    links:
      - udp_receiver
    environment:
      - GCP_PROJECT_ID=deklerk-sandbox
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/deklerk-startup-project/creds.json
      - UDP_RECEIVER_IP=udp_receiver
      - UDP_RECEIVER_PORT=8082
    command:
      - /bin/sh
      - -c
      - |
        go run senders/udp/*.go